// <auto-generated />
namespace SQLiteConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class NameCores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameCores));
        
        string IMigrationMetadata.Id
        {
            get { return "202102110515446_NameCores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
